import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Controller, Scene } from "react-scrollmagic";

export default function Home() {
  const videoRef = useRef(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main1}>
        <div className="section" />
        <div id="trigger" />
      </div>
      <div className={styles.main2}>
        <div className="section" />
        <div id="trigger1" />

        <video width="600" muted preload ref={videoRef}>
          <source
            src={`https://cdn.ananaspizza.de/file/malte-image-store/v9-webm.webm`}
            type="video/webm"
          />
        </video>
        <Controller>
          <Scene
            duration={500}
            classToggle="zap"
            triggerElement="#trigger1"
            indicators={true}
          >
            {(progress, event) => {
              console.log(videoRef?.current);

              if (videoRef !== null) {
                videoRef?.current?.currentTime = progress * 2;
              }
              return <></>;
            }}
          </Scene>
        </Controller>
      </div>
      <div className={styles.main3}>
        <div className="section" />
        <div id="trigger" />
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
